[theme]
base = "dark"
primaryColor = "#facc15"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
